/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/man.glb --transform 
Files: public/models/man.glb [10.88MB] > /home/shafiul/Music/wawasensei code/24-portfolio-starter/man-transformed.glb [530.8KB] (95%)
Author: CreadorDeMu (https://sketchfab.com/creadordemu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rust-space-suit-730cd3ed773b4ce2bd60996d2bd03bd8
Title: Rust - Space Suit
*/

import React, { useEffect, useRef, useState } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import * as THREE from 'three'
import { SkeletonUtils } from 'three-stdlib'

export default function Man(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/man-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  // ['Idle', 'Walk', 'Jump', 'Gun']

  const scrollData = useScroll();
  const lastScroll = useRef(0);
  const currentAnimation = useRef("Idle");

  useEffect(() => {
    actions[currentAnimation.current]?.reset().fadeIn(0.5).play();
    return () => actions[currentAnimation.current]?.fadeOut(0.5);
  }, [actions]);

  useFrame(() => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    const isScrolling = Math.abs(scrollDelta) > 0.0001;
    const nextAnimation = isScrolling ? "Walk" : "Idle";

    if (nextAnimation !== currentAnimation.current) {
      actions[currentAnimation.current]?.fadeOut(0.5);
      actions[nextAnimation]?.reset().fadeIn(0.5).play();
      currentAnimation.current = nextAnimation;
    }

    // Rotation logic
    let targetRotation = 0;
    if (isScrolling) {
      targetRotation = scrollDelta > 0 ? 0 : Math.PI;
    } else {
      targetRotation = 0;
    }

    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      targetRotation,
      0.1
    );

    lastScroll.current = scrollData.offset;
  });



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.SuitMat} skeleton={nodes.Object_7.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.BackpackMat} skeleton={nodes.Object_9.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.HelmetMat} skeleton={nodes.Object_11.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/man-transformed.glb')
